spring:

  application:
    name: ejerciciosBosonit

  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  # Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/bosonit
    username: user
    password: password
  driver:
    class: name:com.mysql.cj.jdbc.Driver # database connection driver
  jpa:
    hibernate:
      ddl-auto: update # create tables automatically
    open-in-view: false
